version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI
      - REPOSITORY_URI=$ECR_REPO_URI
      - IMAGE_TAG=buildimage
      - echo npm install started on `date`
      - npm install
  build:
    commands:
      - IMAGE_NAME=node-web-app-$GIT_BRANCH_NAME
      - echo Build started on `date`
      - echo Building the Docker images...
      - docker build . -t $IMAGE_NAME
      - docker tag $IMAGE_NAME:latest $REPOSITORY_URI:$IMAGE_NAME
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_NAME
      - printf '[{"name":"nodejs-dev","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_NAME >> imagedefinitions.json
artifacts:
  files: imagedefinitions.json
